
"""Utility helpers for reading application log files for the WebUI."""

from __future__ import annotations

import asyncio
from datetime import datetime
from pathlib import Path
from typing import AsyncGenerator, Dict, List, Optional, Tuple

from ..models import LogEntry, LogFileInfo


class LogService:
    """Read and parse log files generated by the application."""

    def __init__(self, log_dir: str = "log") -> None:
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)

    async def get_log_files(self) -> List[LogFileInfo]:
        files: List[LogFileInfo] = []
        for path in sorted(self.log_dir.glob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True):
            stat = path.stat()
            files.append(
                LogFileInfo(
                    name=path.name,
                    path=str(path),
                    size=stat.st_size,
                    modified_time=datetime.fromtimestamp(stat.st_mtime).isoformat(),
                    log_level="INFO",
                )
            )
        return files

    async def get_log_content(
        self,
        file: str,
        limit: int = 100,
        offset: int = 0,
        level: Optional[str] = None,
        search: Optional[str] = None,
    ) -> Dict[str, object]:
        entries = await asyncio.to_thread(self._load_entries, file)
        filtered = self._filter_entries(entries, level=level, search=search)
        total = len(filtered)
        slice_end = offset + limit
        page_entries = filtered[offset:slice_end]
        return {
            "entries": [entry.model_dump() for entry in page_entries],
            "total": total,
            "has_more": slice_end < total,
        }

    async def get_recent_logs(self, limit: int = 10) -> List[Dict[str, object]]:
        entries = await asyncio.to_thread(self._collect_all_entries)
        recent = list(reversed(entries))[:limit]
        return [entry.model_dump() for entry in recent]

    async def search_logs(
        self,
        query: str,
        level: Optional[str] = None,
        limit: int = 100,
    ) -> Dict[str, object]:
        entries = await asyncio.to_thread(self._collect_all_entries)
        filtered = self._filter_entries(entries, level=level, search=query)
        limited = filtered[:limit]
        return {
            "entries": [entry.model_dump() for entry in limited],
            "total": len(filtered),
            "has_more": len(filtered) > len(limited),
        }

    async def get_log_file_path(self, file_name: str) -> Optional[Path]:
        path = self.log_dir / file_name
        return path if path.exists() else None

    def _get_log_file_path(self, file_name: str) -> Path:
        return self.log_dir / file_name

    async def stream_log_entries(
        self,
        file: str,
        poll_interval: float = 1.0,
        start_at_end: bool = True,
    ) -> AsyncGenerator[LogEntry, None]:
        """Yield log entries as they are appended to the requested log file."""
        path = self._get_log_file_path(file)
        if not path.exists():
            raise FileNotFoundError(file)

        position = path.stat().st_size if start_at_end else 0

        try:
            while True:
                if not path.exists():
                    await asyncio.sleep(poll_interval)
                    path = self._get_log_file_path(file)
                    position = 0
                    continue

                size = path.stat().st_size
                if size < position:
                    position = 0

                lines, position = await asyncio.to_thread(
                    self._read_lines_from_position,
                    path,
                    position,
                )

                for line in lines:
                    parsed = self._parse_log_line(line)
                    if parsed:
                        yield parsed

                await asyncio.sleep(poll_interval)
        except asyncio.CancelledError:  # pragma: no cover - cooperative cancellation
            raise
        except GeneratorExit:  # pragma: no cover - generator closed by caller
            return

    def _read_lines_from_position(self, path: Path, position: int) -> Tuple[List[str], int]:
        """Read new lines from the file starting at the provided byte offset."""
        lines: List[str] = []
        new_position = position

        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            handle.seek(position)
            for raw_line in handle:
                lines.append(raw_line.rstrip("\n"))
            new_position = handle.tell()

        return lines, new_position

    def _filter_entries(
        self,
        entries: List[LogEntry],
        level: Optional[str] = None,
        search: Optional[str] = None,
    ) -> List[LogEntry]:
        level_upper = level.upper() if level else None
        search_lower = search.lower() if search else None
        filtered: List[LogEntry] = []
        for entry in entries:
            if level_upper and entry.level != level_upper:
                continue
            if search_lower:
                haystacks = [entry.message.lower()]
                if entry.level:
                    haystacks.append(entry.level.lower())
                if entry.module:
                    haystacks.append(entry.module.lower())
                if search_lower not in " ".join(haystacks):
                    continue
            filtered.append(entry)
        return filtered

    def _collect_all_entries(self) -> List[LogEntry]:
        entries: List[LogEntry] = []
        for path in sorted(self.log_dir.glob("*.log")):
            entries.extend(self._load_entries_from_path(path))
        return entries

    def _load_entries(self, file_name: str) -> List[LogEntry]:
        path = self.log_dir / file_name
        if not path.exists():
            raise FileNotFoundError(file_name)
        return self._load_entries_from_path(path)

    def _load_entries_from_path(self, path: Path) -> List[LogEntry]:
        entries: List[LogEntry] = []
        with path.open("r", encoding="utf-8", errors="ignore") as handle:
            for line in handle:
                line = line.rstrip()
                if not line:
                    continue
                parsed = self._parse_log_line(line)
                if parsed:
                    entries.append(parsed)
        return entries

    def _parse_log_line(self, line: str) -> Optional[LogEntry]:
        parts = [part.strip() for part in line.split("|", maxsplit=2)]
        if len(parts) == 3:
            timestamp_str, level_str, message = parts
            try:
                parsed_dt = datetime.fromisoformat(timestamp_str)
                timestamp_iso = parsed_dt.isoformat(timespec="seconds")
            except ValueError:
                timestamp_iso = datetime.now().isoformat(timespec="seconds")
            level = level_str.upper() if level_str else "INFO"
            return LogEntry(
                timestamp=timestamp_iso,
                level=level,
                message=message,
                module=None,
                line_number=None,
                thread_id=None,
            )

        return None


_log_service: Optional[LogService] = None


def get_log_service() -> LogService:
    global _log_service
    if _log_service is None:
        _log_service = LogService()
    return _log_service


log_service = get_log_service()
